lesson01
SvetaPiven/it-academy-java1 pull request #3
Opened 2022-09-11 20:25 UTC by SvetaPiven

2022-09-12 12:19 UTC, rakovets requested changes
need to fix

2022-09-12 12:19 UTC, rakovets commented on lesson01/src/task03.java
> +public class task03 {
```suggestion
public class Task03 {
```

2022-09-12 12:19 UTC, rakovets commented on lesson01/src/task04.java
> +public class task04 {
```suggestion
public class Task04 {
```

2022-09-16 06:43 UTC, SvetaPiven commented on lesson01/src/task03.java
> +public class task03 {
Task1 fixed

2022-09-16 06:44 UTC, SvetaPiven commented on lesson01/src/task04.java
> +public class task04 {
Task2 fixed

2022-10-03 11:22 UTC, merged